"""Rename createdAt and updateAt to created_at and updated_at

Revision ID: 2d6f4945a9ff
Revises: 72d5be84b49b
Create Date: 2025-05-22 02:21:44.251331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d6f4945a9ff"
down_revision: Union[str, None] = "72d5be84b49b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("tasks", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("tasks", "updatedAt")
    op.drop_column("tasks", "createdAt")
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("users", "updatedAt")
    op.drop_column("users", "createdAt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "createdAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updatedAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.add_column(
        "tasks",
        sa.Column(
            "createdAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "updatedAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("tasks", "updated_at")
    op.drop_column("tasks", "created_at")
    # ### end Alembic commands ###
